### ISSUE TITLE
Keyring File Modification Date Incorrectly Updated

### ISSUE THREAD

**Issue by miluxhd** [puppetlabs/puppetlabs-apt#1196]
## Bug

The keyring file /etc/apt/keyrings/percona unexpectedly has its modification date (mtime) altered every time the Puppet catalog is applied. this behavior is inconsistent with expected behavior, where the content should only change if the file content is actually modified.
```
Notice: /Stage[main]/Server::Apt/Apt::Source[percona80]/Apt::Keyring[percona]/File[/etc/apt/keyrings/percona]/content: 

Notice: /Stage[main]/Server::Apt/Apt::Source[percona80]/Apt::Keyring[percona]/File[/etc/apt/keyrings/percona]/content: content changed '{mtime}2024-09-04 16:18:08 +0200' to '{mtime}2024-09-04 16:22:42 +0200'
Notice: Applied catalog in 2.25 seconds

```
## Steps to Reproduce
Configure an apt source in Puppet with a GPG key that redirects to another URL (as in the provided example): 
```
class server::apt($sources = {}) {

  if ! empty($sources) {
    create_resources('apt::source',$sources)
  }
}
```

```
server::apt::sources:
  percona80:
    location: 'http://repo.percona.com/ps-80/apt'
    repos: 'main'
    key:
      name: 'percona'
      source: 'https://github.com/percona/percona-repositories/raw/main/deb/percona-keyring.gpg'
    include:
      deb: true
```

## Environment
 - puppet version: 8.8.1
 - Platform: Debian 

## Additional Context
It doesn't show changes when I change the timestamp of key files to future.

`touch -d "2124-08-29 12:53:46 +0200"  /etc/apt/keyrings/*
`
