### ISSUE TITLE
Required gnupg package installation fails when sources purging is enabled

### ISSUE THREAD

**Issue by jay7x** [puppetlabs/puppetlabs-apt#1205]
## Describe the Bug
When purging is enabled, Apt module fails to install the `gnupg` package, because existing repos are purged already, but no new repos installed yet. Overall that causes every resource (`package` mainly) depending on the Apt class to fail this run (except repos). Next run Apt will install `gnupg` just fine, because repos are already there.

It seems, `gnupg` is not required anymore on any supported Debian flavor atm. So maybe easy fix is just to drop it. But I'm not 100% sure.

## Expected Behavior
To be able to install repos and packages in a single run.

## Steps to Reproduce
1. Enable purging sources in Apt:
  ```yaml
  apt::purge:
    sources.list: true
    sources.list.d: true
  ```
2. Configure a main Debian/Ubuntu repo with apt::sources:
```yaml
apt::sources:
  debian:
    location: http://deb.debian.org/debian
    release: "%{facts.os.distro.codename}"
    repos: "main"
```

3. Apply `include apt`.

## Environment
 - Agent version: 8.8.1
 - Platform: Debian 11
 - puppetlabs/apt version: 9.4.0
