### ISSUE TITLE
some repositories need $repos to be empty value but limit doesn't allow for that

### ISSUE THREAD

**Issue by XANi** [puppetlabs/puppetlabs-apt#1225]
## Describe the Bug

```
    qownnotes:
        comment: QOwnNotes
        location: http://download.opensuse.org/repositories/home:/pbek:/QOwnNotes/Debian_11/
        release: /
        repos: ""
```
stopped working. This particular package repository doesn't need/use release/repos at all:

http://download.opensuse.org/repositories/home:/pbek:/QOwnNotes/Debian_11/
https://www.qownnotes.org/installation/debian.html

and similar problem for

https://pkg.origin.jenkins.io/debian/

APT has no problems with it

```deb [arch=${ARCHITECTURE} signed-by=${SIGNED_BY}] http://download.opensuse.org/repositories/home:/pbek:/QOwnNotes/Debian_12/ /```

and it worked in previous versions, but in 10.0.0/10.0/1 just gives me
```
Error: Evaluation Error: Error while evaluating a Resource Statement, Apt::Source[qownnotes]: parameter 'repos' expects a value of type String[1] or Array[String[1]], got String (file: /var/lib/dpp/repos/public/modules/core/manifests/init.pp, line: 34) 
```

passing string containing one space works as workaround
